### PR TITLE
rename sample playbooks, delete duplicate

### PR DESCRIPTION
**Pull request by yungezz**
## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## How to Test
*  Install ansible

```bash
$ pip install ansible[azure]
```

*  [Optional] Install ansible role

```bash
$ ansible-galaxy install Azure.azure_preview_modules
$ pip install -r ~/.ansible/roles/Azure.azure_preview_modules/files/requirements-azure.txt
```

*  Get the sample playbook

```
git clone https://github.com/Azure-Samples/ansible-playbooks.git
cd ansible-playbooks
git checkout [branch-name]
```

* Test the code

```bash
ansible-playbook <filename>.yml
```

## What to Check
Verify that the playbook is successfully run.

### CODE REVIEW

**Comment by Fred-sun** [comment]
@kyliel This PR need you review, Could you help to check it？

**Comment by Fred-sun** [comment]
@kyliel Could you help review this PR? Thanks!

**Comment by yungezz** [comment]
@Fred-sun  I'll take care of this one. thanks.

**Comment by Fred-sun** [comment]
Thanks @yungezz

**Comment by Fred-sun** [comment]
@yungezz Could you help confirm this PR finish review and go to next step forward? Thanks!

**Comment by Fred-sun** [comment]
@yungezz Could you help to update the PR status? Thanks1

**Comment by yuwzho** [comment]
@Fred-sun Please skip this PR since @yungezz will take care of this one

**Comment by Fred-sun** [comment]
@yuwzho Ok, I will ,Thanks!

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz Could you help resolve the conflicting files and push to merged? Thanks!

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz Could you help resolve the conflicting files and push for merge? Thanks!

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz Please help resolve the conflicting files and push for review when you're available. Thanks!

**Comment by Fred-sun** [comment]
@yungezz Could you help resolve the conflicting files when you're available?  and push for review. Thanks!

**Comment by Fred-sun** [comment]
@yungezz need_update

**Comment by Fred-sun** [comment]
ping

**Pull request closed without merging**
