### PR TITLE
Adding support for 2.8

### PR DESCRIPTION
**Pull request by imjoseangel**
## Purpose
* Generalizes VM from azure_rm_virtualmachine instead from the API.
* Uses new azure_rm_virtualmachineextension module.
* ...

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## How to Test
*  Install ansible

```bash
$ pip install ansible[azure]
```

*  [Optional] Install ansible role

```bash
$ ansible-galaxy install azure.azure_preview_modules
$ pip install -r ~/.ansible/roles/azure.azure_preview_modules/files/requirements-azure.txt
```

*  Get the sample playbook

```
git clone https://github.com/Azure-Samples/ansible-playbooks.git
cd ansible-playbooks
git checkout [branch-name]
```

* Test the code

```bash
ansible-playbook vm_create_image.yml
```

## What to Check
Verify that the playbook is successfully run.

```
TASK [Create VM Extension] *************************************************************************************************************************************************************

changed: [localhost]

TASK [Stop VM before it can be generalized and image captured] *************************************************************************************************************************
changed: [localhost]

TASK [Generalize VM using version >= 2.8] **********************************************************************************************************************************************
changed: [localhost]

TASK [Create an image from a virtual machine] ******************************************************************************************************************************************
changed: [localhost]
```

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @zikalino @yuwzho @MyronFanQiu Please take a review this PR when you're free! Thanks a lot!

**Comment by imjoseangel** [comment]
Hey! How is this going? Could you please review? Thanks!

**Comment by zikalino** [comment]
Looks great! Thank you for contribution @imjoseangel

**Pull request merged**
